networks:
  network_oop1:
    name: network_oop1

services:
  nginx_oop1:
    container_name: nginx_oop1
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    networks:
      - network_oop1
    depends_on:
      - php_oop1
      - mysql_oop1

  php_oop1:
    container_name: php_oop1
    build: ./images/php
    volumes:
      - ./www:/var/www/public_html
    networks:
      - network_oop1
    depends_on:
      - mysql_oop1

  mysql_oop1:
    container_name: mysql_oop1
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network_oop1

  phpmyadmin2:
    container_name: phpmyadmin_oop1
    image: phpmyadmin
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql_oop1
    networks:
      - network_oop1
    depends_on:
      - mysql_oop1
